AWSTemplateFormatVersion: 2010-09-09

Parameters:
  BucketName:
    Description: Bucket Name (must be globally unique)
    Type: String

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true           
        IgnorePublicAcls: true          
        BlockPublicPolicy: false        
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins: ["*"]
            AllowedMethods: ["GET"]
            AllowedHeaders: ["*"]
            MaxAge: 3600
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub arn:aws:s3:::${S3Bucket}/*

Outputs:
  WebsiteURL:
    Description: URL for website hosted on S3 (HTTP website endpoint)
    Value: !GetAtt S3Bucket.WebsiteURL
